### PR TITLE
[AUS] Update langpacks to 27.1.0

### PR DESCRIPTION
**Pull request by wolfbeast**
This also adds en-GB and ko

### CODE REVIEW

**Comment by Lootyhoof** [comment]
`en-GB` has issues with the strings it was initially provided (some weren't mapped correctly it seems), so while this is 100% translated some strings and modifier keys(!) aren't set up as they should.

It's not release-ready.

**Comment by wolfbeast** [comment]
I'll pull en-GB. @JustOff please make sure stuff is actually release ready and verified before telling me to publish, thanks.

**Comment by JustOff** [comment]
Unfortunately I can't do nothing with such cases. en-GB language pack was [processed](https://crowdin.com/project/pale-moon/en-GB/activity) solely by @Lootyhoof and now he found that it's not ready because of data that were imported from PM 26.x.

**Comment by Lootyhoof** [comment]
I'm currently verifying (and fixing) as I find time. Once it's 100% verified it will be release-ready.

**Comment by JustOff** [comment]
To be honest I'm not sure that everything was so bad that it was absolutely necessary to remove en-GB from APMO completely. We all trying to do our best, but no one can be perfect and other language packs are not perfect too.

**Comment by mattatobin** [comment]
I have to ask what other potential issues are there with the other langpacks that were not checked and verified. You say they are not perfect.. But one must realize that imperfect langpacks will absolutely break the browser or mislead users in the case of wrongly assigned strings.

This is not something that can be fudged or half-assed. It has to be valid and correct. Sure there may be untranslated strings here and there but none can be missing or assigned incorrectly. That would be unacceptable.

Trying to pass the buck of responsibility for this incident to Ryan is unfair. As noted you did not bother to check with him. Your position is something to the ring of Localization Coordinator. Thus, your job is to work with translators and ensuring things are done properly. Checking with Ryan before signing off on it is at the very essence of your job description. 

It would be like taking a series of patches from BMO and a BSD rebuild and blindly applying them to the codebase with little regard to anything else assuring everyone things are just jim dandy fantastic.

Take this as seriously as I present it and learn from it. You aren't the first one to screw up but do please for the same of the Project, Team Members, and users to not make a habit of this.

**Comment by JustOff** [comment]
Sorry, but it seems that you have no idea how the localization process is currently going. If you really want to understand with this please be sure to read [here](https://forum.palemoon.org/viewtopic.php?f=30&t=13627) and [there](https://forum.palemoon.org/viewtopic.php?f=30&t=13720).

Obviously you also don't know what exactly the problem occurred with the en-GB locale, so your commonplace remarks have no sense. Please let us deal with this situation without your preachments.

**Comment by wolfbeast** [comment]
As far as I understood there were issues with access keys. that can and will cause usability problems, so that is why I removed the langpack for the time being.

**Comment by JustOff** [comment]
@wolfbeast you are right, here's updates made by @Lootyhoof since then: [1](https://crowdin.com/translate/pale-moon/213/enus-engb#5079), [2](https://crowdin.com/translate/pale-moon/311/enus-engb#8437), [4](https://crowdin.com/translate/pale-moon/311/enus-engb#8437), [5](https://crowdin.com/translate/pale-moon/275/enus-engb#7373), [6](https://crowdin.com/translate/pale-moon/311/enus-engb#8441), [7](https://crowdin.com/translate/pale-moon/311/enus-engb#8439). I believe that they are not critical, but he is entitled to decide that they are important enough to recognize the en-GB locale is not good for release.

It's sad that those errors were not found during final testing after [pre-release was published at January 22](https://forum.palemoon.org/viewtopic.php?p=104285#p104285), but no one is trying to blame someone or shift the responsibility.

We are moving forward and as soon as Ryan will decide that all the corrections are done new language pack will be published for the test and then proposed for the release.

**Comment by wolfbeast** [comment]
I'm not blaming anyone. Just saying what I did because there were clear signals that there are known critical issues with it. Why is everyone taking anything I say so personal these last few days?

**Comment by JustOff** [comment]
@wolfbeast  I'm sorry if you got the impression that [that post](https://github.com/Pale-Moon-Addons-Team/phoebus/pull/39#issuecomment-279221100) was related to you, while it was the response to @mattatobin's [intervention](https://github.com/Pale-Moon-Addons-Team/phoebus/pull/39#issuecomment-279204541). And I apologize that you've had to read it all.

**Pull request merged**
