### PR TITLE
[SITE] Add "Greedy Cache"

### PR DESCRIPTION
**Pull request by JustOff**
All corresponding files were uploaded on ftp. Thank you in advance.

### CODE REVIEW

**Comment by mattatobin** [comment]
Was this previously provisioned by the Add-ons Team?

**Comment by JustOff** [comment]
In my previous PR, I was guided by information from [here](https://github.com/Pale-Moon-Addons-Team/phoebus/pull/20). Since everything went well and without any remarks, I concluded that this method is acceptable. I'm not aware how it works from inside, so please correct me if I did something wrong.

**Comment by mattatobin** [comment]
Yeah, I had to fix that when that happened.. Moonchild isn't actually trained on Add-ons Team procedure. Of course I would be more than happy to take him through it. However, he has a lot to keep in his head as it is to be bothered with yet another set of instructions or whatnot.. Besides, that is why there is an Add-ons Team.

**Comment by wolfbeast** [comment]
>  Moonchild isn't actually trained on Add-ons Team procedure.

$$CRITICAL: Quota reached.

**Pull request merged**
