### PR TITLE
[SITE] Add "YouTube Lazy Load"

### PR DESCRIPTION
**Pull request by JustOff**
All corresponding files were uploaded on ftp. Thank you in advance.

### CODE REVIEW

**Comment by Lootyhoof** [comment]
Thanks!

**Comment by JustOff** [comment]
Thank you, but I don't see it on site yet. Or I'm just too impatient?)

**Comment by Lootyhoof** [comment]
Possibly the latter. ;)

http://addons.palemoon.org/extensions/youtube-lazy-load/

**Comment by wolfbeast** [comment]
Pushing to production can take an hour before it's live (because of cron jobs to publish)

**Comment by JustOff** [comment]
I'd like to suggest one more add-on, but I see that TRUNK is busy by development of Phoebus 1.5. Which branch can I use for PR now (LIVE/RELEASE/else)?

**Comment by mattatobin** [comment]
use RELEASE also check the default branch.. I have created a readme

**Comment by JustOff** [comment]
Thanks.

**Comment by mattatobin** [comment]
Did Ryan or Andy explain how this process works.. You need to let them provision the FTP folder and datastore folder before adding anything to the db arrays. Creating a directory in FTP before that happens creates more work for the Add-ons Team.

**Pull request merged**
