### PR TITLE
[SITE] Add Expose Noisy Tabs

### PR DESCRIPTION
**Pull request by wsdfhjxc**
I dared to upload the [extension](https://github.com/wsdfhjxc/expose-noisy-tabs) and its metadata to my account on the FTP server, but let me know if this way of add-on submission is not welcome and I'll remove it immediately.

### CODE REVIEW

**Comment by Lootyhoof** [comment]
I don't appear to see your add-on on the server currently. Where did you upload it to?

**Comment by wsdfhjxc** [comment]
I've created a directory in wsdfhjxc@regolith.server.binocnetwork.com next to color-my-tabs and crush-those-cookies directories. The fact is Tobin dealt with previous ones in the past and maybe this required some additional processing, but since he is not available for a while, I though it'll be fine to just put the new one's data next to others, especially because changes made inside these directories are instantly visible on APMO.

**Comment by Lootyhoof** [comment]
If you say it's there then I trust you're correct; the commit here all looks OK too.

Do note however that changes here aren't immediately live on the server; there's some backend work that must be done that I'm not (yet) familiar with, so will need someone to take care of.

**Comment by wsdfhjxc** [comment]
The base path for extensions' directories is addons.palemoon.org/datastore/extensions, so I guess directories placed  inside a named FTP account have to be symlinked to that location to get visible. If that's the case, then it should be done before merging into LIVE.

The last thing I want is to break something in here, so it'd be great if @mattatobin could take a look at this.

Thanks for your time!

**Comment by wolfbeast** [comment]
Hmm I gathered what was in trunk could be put live - was that an error?

**Comment by wolfbeast** [comment]
Looks like the stuff from ftp wasn't copied over for expose noisy tabs. I've just done that.

**Comment by wsdfhjxc** [comment]
Great, thank you!

Could this also be linked with the directory placed inside the named FTP account to make future updates possible? Currently, changes made there are not visible in the datastore.

**Comment by wolfbeast** [comment]
I just made a copy as a quick fix. it should probably be symlinked instead. @agilbertson1977 probably has more details and/or time to actually do it the way it's supposed to be done -- I know very little about the working of the addons site.

**Pull request merged**
